### ISSUE TITLE
to_case() - Fail with words with accent mark

### ISSUE THREAD

**Issue by trapalleiro-git** [rutrum/convert-case#8]
to_case() fail with words With accent mark. Example: música moderna.

**Comment by rutrum** [comment]
I have added `unicode-segmentation` as a dependency, and added a test which specifically addresses the string you provided. The newest version, convert-case version 0.6.0 fixes this issue. https://github.com/rutrum/convert-case/blob/a8702a05217664ca59cb7471df68a91dcf4b91ee/src/lib.rs#L650-L653
