### ISSUE TITLE
Is there a way to not insert `_` between number and character?

### ISSUE THREAD

**Issue by duskmoon314** [rutrum/convert-case#9]
I have some strings like `uart0` and need to convert to `UpperSnake` in some cases. So I search and find this wonderful crate. But when using it, the result I get is like `UART_0`.

I wonder is there a way to avoid this? Maybe a flag or some methods in this crate?

**Comment by duskmoon314** [comment]
Sorry, I haven't noticed the [Boundary Specificity](https://docs.rs/convert_case/0.5.0/convert_case/#boundary-specificity) section. 😢

**Comment by rutrum** [comment]
Hi duskmoon, you caught me mid response!  I'm glad you were able to find it.  Thanks for reaching out.
